### ISSUE TITLE
heredocs-0.1.3.1 test suite failure

### ISSUE THREAD

**Issue by peti** [cutsea110/heredoc#3]
Citing from http://hydra.cryp.to/build/1952633/nixlog/3/raw:

```
running tests
Running 1 test suites...
Test suite doctest: RUNNING...

<no location info>: error: can't find file: test/Test.hs
Test suite doctest: FAIL
```

**Comment by cutsea110** [comment]
Hmm. i look this just now.

I've been using ghc 8.0.1.
And I fail to cabal test.

**Comment by cutsea110** [comment]
fix it. https://github.com/cutsea110/heredoc/commit/ae57e27bde3b5aae1f163b585f42e5ac36f78d06

I'd like to close this issue, after confirm [hackage server build reports passed](https://hackage.haskell.org/package/heredocs-0.1.4/reports/)
